//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barbershopmanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETGIOHANG
    {
        public int CHITIETGIOHANGID { get; set; }
        public int GIOHANGID { get; set; }
        public int DICHVUID { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual GIOHANG GIOHANG { get; set; }
    }
}
