//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barbershopmanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT_SERVICES
    {
        public int ID { get; set; }
        public int USERID { get; set; }
        public int DICHVUID { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual USER USER { get; set; }
    }
}
